name: Hello World!

on:
  workflow_dispatch

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Current Time
        run: |
          date
      - name: Directory Content
        run: |
          ls -l
