name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: get commit messages
        if: ${{ github.event_name == 'pull_request' }}
        id: get_commits
        run: |
          commits=$(git log --format=%B -n 10)
          echo "commits=$commits" >> $GITHUB_ENV
      - name: Skip deployment if
        if: ${{ github.event_name == 'pull_request' && contains(env.commits, '#skip') }}
        run: |
          echo "skipping deployment since #skip found in commit message"
          exit 0 
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Make production build
        run: npm run build
      - name: Test code
        run: npm run test
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
  tag_release:
    needs: simple_deployment_pipeline
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: '0'

    - name: Bump version and push tag
      if: ${{ github.event_name == 'push' }}
      uses: anothrNick/github-tag-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        
      
      
